### PR TITLE
update to null-safety

### PR DESCRIPTION
**Pull request by liubaishui**

### CODE REVIEW

**Comment by mythz** [comment]
Wow, this large PR to enable null safety is much appreciated. I'll look at merging it after next release as it needs to be deployed in tandem with the Server that can optionally be configured to generate null-safe DTOs as well.

**Comment by tobiaszuercher** [comment]
since other dart libraries are migrating to dart 2.12 <= , we get problems with transient dependencies. if by any chance this can get some priority, this would help a lot for dart-servicestack users! thanks!

**Comment by mythz** [comment]
@tobiaszuercher it will still be a while before we can get to this & server generation, but what transient dependency issues are you referring to, this library's only runtime dependency is already referencing the latest `http: ^0.13.3`?

**Comment by mythz** [comment]
FYI v2.0.0 of [servicestack](https://pub.dev/packages/servicestack) with null safety support is now available on pub.

It should be used with Dart null safe DTOs generated from ServiceStack **v5.11.1+** that's now [available on MyGet](https://docs.servicestack.net/myget).

All existing tests are now passing using the latest DTOs so it should be safe to upgrade, if you run into any issues please report them to https://github.com/ServiceStack/Issues

**Comment by tobiaszuercher** [comment]
awesome @mythz  and thank you! sorry for letting you down & not answering. looking forward to upgrade very soon

**Comment by liubaishui** [comment]
awesome @mythz thank you!

**Pull request merged**
